name: rpiplay
version: git
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

base: core20
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  rpiplay:
    plugin: cmake
    source-type: git
    source: https://github.com/FD-/RPiPlay.git
    build-packages:
      - g++
      - make
      - cmake
      - libavahi-compat-libdnssd-dev 
      - libplist-dev 
      - libssl-dev
      - libgstreamer1.0-dev 
      - libgstreamer-plugins-base1.0-dev 
      - gstreamer1.0-libav
      - gstreamer1.0-vaapi 
      - gstreamer1.0-plugins-bad
      - libffi-dev
      - libffi7
    stage-packages:
      - libavahi-compat-libdnssd-dev 
      - libplist-dev 
      - libssl-dev
      - libgstreamer1.0-dev 
      - libgstreamer-plugins-base1.0-dev 
      - gstreamer1.0-libav
      - gstreamer1.0-vaapi 
      - gstreamer1.0-plugins-bad
      - libffi-dev
      - libffi7
apps:
  test-rpiplay:
    command: rpiplay
